#!/usr/bin/env python3
"""api-auth-sync — keep OAuth tokens fresh for OpenCode + Prime Agent.

Why: OAuth refresh tokens can rotate and be single-use. The live auth.json files are therefore the source of truth;
sops-nix only deploys seed JSONs into the state dir.

Subcommands:
  status    per-entry token expiry in days (no values printed)
  migrate   HM writeBoundary hook: ensure live auth files are REAL regular
            files (convert sops symlinks), freshest-wins restore from
            backup/seed, then update backups
  guard     alias of migrate (cheap, no network)
  refresh   refresh stale OpenAI/Anthropic token lineages, write back
            atomically, update backups

Sources: sops-nix deploys the seed JSONs straight into the state dir
(homeTarget = .local/state/codex-auth/<name>.json); the tool never touches
the dotfiles repo or sops itself.

Security: token/key values are NEVER printed or logged; only paths, provider
keys and expiry deltas. All writes are atomic (tmp + fsync + rename), mode 0600.
"""

import argparse
import fcntl
import json
import os
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path

# NOTE: this file contains NO machine-specific paths. Every path comes from the
# JSON config pointed to by $API_AUTH_CONFIG (generated by module/home.nix).
CONFIG_ENV = "API_AUTH_CONFIG"

OAUTH_PROVIDERS = {
    "openai": ("app_EMoamEEZ73f0CkXaXp7hrann", "https://auth.openai.com/oauth/token"),
    "anthropic": ("9d1c250a-e61b-44d9-88ed-5944d1962f5e", "https://platform.claude.com/v1/oauth/token"),
}
REFRESH_MARGIN_SECS = 48 * 3600
DEFAULT_TTL_SECS = 10 * 86400  # observed access-token lifetime
PERMANENT_CODES = {
    "refresh_token_expired",
    "refresh_token_invalidated",
    "refresh_token_reused",
    "invalid_grant",
    "app_session_terminated",
}
@dataclass
class Entry:
    name: str
    live: Path          # live auth file (real file, never a symlink)
    key: str            # provider key inside the JSON doc
    provider: str = "openai"
    optional: bool = False


# Runtime configuration (single source of truth: the JSON config file).
CONFIG: dict = {}
STATE_DIR: Path = Path("/dev/null")
BACKUP_DIR: Path = Path("/dev/null")
ENTRIES: list = []


def load_config() -> None:
    """Populate STATE_DIR / BACKUP_DIR / ENTRIES from the JSON config."""
    global CONFIG, STATE_DIR, BACKUP_DIR
    raw = os.environ.get(CONFIG_ENV)
    if not raw:
        sys.exit(
            f"error: {CONFIG_ENV} is not set. Point it at the JSON config generated by "
            "packages/api-auth-sync/module/home.nix (programs.api-auth-sync), e.g. the profile-wrapped "
            "binary already has it set."
        )
    try:
        with open(raw) as f:
            CONFIG = json.load(f)
    except (OSError, json.JSONDecodeError) as ex:
        sys.exit(f"error: cannot read config {raw}: {ex}")

    state = CONFIG.get("state_dir") or (
        Path(os.environ.get("XDG_STATE_HOME") or (Path.home() / ".local/state")) / "codex-auth"
    )
    STATE_DIR = Path(state)
    BACKUP_DIR = STATE_DIR / "backup"

    for e in CONFIG.get("entries") or []:
        ENTRIES.append(Entry(str(e["name"]), Path(e["live"]), str(e["key"]), e.get("provider", "openai"), e.get("optional", False)))
    if not ENTRIES:
        sys.exit("error: config defines no entries")
    if any(e.provider not in OAUTH_PROVIDERS for e in ENTRIES):
        sys.exit("error: unsupported OAuth provider in config")


def log(msg: str) -> None:
    stamp = time.strftime("%Y-%m-%dT%H:%M:%S%z")
    print(f"[api-auth-sync {stamp}] {msg}", flush=True)


def ensure_dirs() -> None:
    for d in (STATE_DIR, BACKUP_DIR):
        d.mkdir(parents=True, exist_ok=True)
        try:
            d.chmod(0o700)
        except OSError:
            pass


def norm_ms(v) -> float:
    """Normalize an expiry value to epoch milliseconds (accepts s or ms)."""
    try:
        v = float(v)
    except (TypeError, ValueError):
        return 0.0
    if v <= 0:
        return 0.0
    if v < 1e12:  # seconds
        v *= 1000.0
    return v


def creds_of(doc, key: str):
    """Extract the normalized OAuth triple for one provider key. No values leave this function."""
    if not isinstance(doc, dict):
        return None
    blob = doc.get(key)
    if not isinstance(blob, dict):
        return None
    refresh = blob.get("refresh")
    if not refresh or not isinstance(refresh, str) or blob.get("type") != "oauth":
        return None
    return {
        "access": blob.get("access") or "",
        "refresh": refresh,
        "expires_ms": norm_ms(blob.get("expires")),
        "account_id": blob.get("accountId"),
    }


def load_doc(path: Path):
    """Read a JSON doc through symlinks. Returns (doc, err_reason)."""
    try:
        return json.loads(path.read_text()), None
    except FileNotFoundError:
        return None, "missing"
    except json.JSONDecodeError as ex:
        return None, f"invalid json ({ex.msg})"
    except OSError as ex:
        return None, f"unreadable ({ex.strerror})"


def write_json_atomic(path: Path, doc, mode: int = 0o600) -> None:
    """Atomically write a real regular file; os.replace over a symlink replaces the link itself."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.parent / f".{path.name}.tmp-{os.getpid()}"
    with open(tmp, "w") as f:
        json.dump(doc, f, indent=2)
        f.write("\n")
        f.flush()
        os.fsync(f.fileno())
    os.chmod(tmp, mode)
    os.replace(tmp, path)


def days_left(expires_ms: float) -> float:
    return (expires_ms - time.time() * 1000) / 86_400_000.0


# ---------------------------------------------------------------- candidates

class Source:
    __slots__ = ("name", "path", "doc", "creds", "err")

    def __init__(self, name, path, doc, err):
        self.name, self.path, self.doc, self.err = name, path, doc, err
        self.creds = creds_of(doc, doc_key.get(path)) if doc is not None else None


# map path -> provider key (needed by Source before entries are wired in)
doc_key: dict = {}


def entry_paths(e: Entry):
    return {
        "live": e.live,
        "backup": BACKUP_DIR / f"{e.name}.json",
        "seed": STATE_DIR / f"{e.name}.json",
    }


def collect_sources(e: Entry):
    doc_key[e.live] = e.key
    doc_key[BACKUP_DIR / f"{e.name}.json"] = e.key
    doc_key[STATE_DIR / f"{e.name}.json"] = e.key
    out = []
    for name, path in entry_paths(e).items():
        doc, err = load_doc(path)
        out.append(Source(name, path, doc, err))
    return out


def pick_freshest(sources):
    valid = [s for s in sources if s.creds is not None]
    if not valid:
        return None
    return max(valid, key=lambda s: (s.creds["expires_ms"], s.name == "live"))


def update_backup(e: Entry, doc) -> None:
    """Keep the state backup in sync with a fresher live doc."""
    bpath = BACKUP_DIR / f"{e.name}.json"
    bdoc, _ = load_doc(bpath)
    lc = creds_of(doc, e.key)
    bc = creds_of(bdoc, e.key) if bdoc is not None else None
    if lc and (bc is None or lc["expires_ms"] > bc["expires_ms"]):
        merged = dict(bdoc) if isinstance(bdoc, dict) else {}
        merged[e.key] = doc[e.key]
        write_json_atomic(bpath, merged)
        log(f"{e.name}: backup updated (~{days_left(lc['expires_ms']):.1f}d left)")


# ---------------------------------------------------------------- commands

def cmd_status(_args) -> int:
    ensure_dirs()
    for e in ENTRIES:
        print(f"{e.name} (provider key '{e.key}'):")
        for s in collect_sources(e):
            if s.creds is None:
                print(f"  {s.name:7s} {s.path}: unavailable ({s.err or 'no refresh token'})")
            else:
                print(f"  {s.name:7s} {s.path}: ~{days_left(s.creds['expires_ms']):.1f}d left")
    return 0


def cmd_migrate(_args) -> int:
    """writeBoundary hook: live paths must be real regular files, freshest wins."""
    ensure_dirs()
    rc = 0
    for e in ENTRIES:
        sources = collect_sources(e)
        live = next(s for s in sources if s.name == "live")
        bad = e.live.is_symlink() or live.doc is None
        best = pick_freshest(sources)
        if bad and best is None:
            if not e.optional:
                log(f"{e.name}: live file was unavailable and no usable source found")
                rc = 1
            continue
        if best is not None:
            # Merge only the managed credential. Replacing a whole auth.json
            # can clobber another provider refreshed by the application.
            current, _ = load_doc(e.live)
            current = current if isinstance(current, dict) else {}
            local = creds_of(current, e.key)
            if bad or local is None or best.creds["expires_ms"] > local["expires_ms"]:
                current[e.key] = best.doc[e.key]
                write_json_atomic(e.live, current)
                log(f"{e.name}: adopted '{best.name}' credential")
        doc, _ = load_doc(e.live)
        if doc is None:
            log(f"{e.name}: live file unreadable after migration")
            rc = 1
            continue
        update_backup(e, doc)
    return rc


def acquire_lock():
    fd = os.open(STATE_DIR / "refresh.lock", os.O_CREAT | os.O_RDWR, 0o600)
    try:
        fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        return fd
    except BlockingIOError:
        os.close(fd)
        return None


def http_refresh(provider: str, refresh_token: str):
    """POST the provider refresh request. Never log token response bodies."""
    client_id, token_url = OAUTH_PROVIDERS[provider]
    payload = json.dumps({
        "grant_type": "refresh_token",
        "client_id": client_id,
        "refresh_token": refresh_token,
    }).encode()
    req = urllib.request.Request(token_url, data=payload,
                                 headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.loads(r.read().decode())
    except urllib.error.HTTPError as ex:
        try:
            code = json.loads(ex.read().decode()).get("code", "")
        except Exception:
            code = ""
        if ex.code in (400, 401) and code in PERMANENT_CODES:
            raise PermanentError(code)
        raise TransientError(f"http {ex.code}")
    except urllib.error.URLError:
        raise TransientError("network error")
    except TimeoutError:
        raise TransientError("timeout")


class PermanentError(Exception):
    pass


class TransientError(Exception):
    pass


def cmd_refresh(args) -> int:
    ensure_dirs()
    lock = acquire_lock()
    if lock is None:
        log("another refresh is already running; exiting")
        return 0
    rc = 0
    try:
        # gather freshest state per entry, adopting non-live sources into live
        plan = []
        for e in ENTRIES:
            sources = collect_sources(e)
            best = pick_freshest(sources)
            if best is None:
                if not e.optional:
                    log(f"{e.name}: no usable refresh token found anywhere; skipping")
                    rc = max(rc, 1)
                continue
            doc, _ = load_doc(e.live)
            doc = doc if isinstance(doc, dict) else {}
            live_creds = creds_of(doc, e.key)
            if live_creds is None or best.creds["expires_ms"] > live_creds["expires_ms"]:
                doc[e.key] = best.doc[e.key]
                write_json_atomic(e.live, doc)
                log(f"{e.name}: adopted fresher credential from '{best.name}'")
            plan.append((e, creds_of(doc, e.key)))

        # group entries by refresh token lineage: same token -> exactly ONE network call
        groups = {}
        for e, creds in plan:
            groups.setdefault((e.provider, creds["refresh"]), []).append((e, creds))

        now_ms = time.time() * 1000
        for (provider, token), members in groups.items():
            freshest = max(members, key=lambda m: m[1]["expires_ms"])
            left_secs = freshest[1]["expires_ms"] / 1000.0 - time.time()
            if left_secs > REFRESH_MARGIN_SECS:
                log(f"{freshest[0].name}: token fresh (~{left_secs / 86400:.1f}d left); no network call")
                continue
            try:
                resp = http_refresh(provider, token)
            except PermanentError as ex:
                log(f"{freshest[0].name}: PERMANENT refresh failure ({ex}); browser re-login required")
                rc = 3
                continue
            except TransientError as ex:
                log(f"{freshest[0].name}: transient refresh failure ({ex}); will retry later")
                rc = max(rc, 4)
                continue
            new_access = resp.get("access_token")
            if not new_access:
                log(f"{freshest[0].name}: refresh response had no access_token; retry later")
                rc = max(rc, 4)
                continue
            new_refresh = resp.get("refresh_token") or token  # rotation: persist the new one
            try:
                ttl = float(resp.get("expires_in") or (DEFAULT_TTL_SECS if provider == "openai" else 0))
            except (TypeError, ValueError):
                ttl = 0
            if provider == "anthropic" and (not resp.get("refresh_token") or ttl <= 0):
                log(f"{freshest[0].name}: incomplete Anthropic refresh response; retry later")
                rc = max(rc, 4)
                continue
            new_expires_ms = now_ms + ttl * 1000.0
            if provider == "anthropic":
                new_expires_ms -= 5 * 60 * 1000
            for e, _creds in members:
                # Re-read before each write: Prime Agent can refresh another
                # provider in the same auth.json while this request is running.
                doc, _ = load_doc(e.live)
                doc = doc if isinstance(doc, dict) else {}
                current = creds_of(doc, e.key)
                if current and current["expires_ms"] > freshest[1]["expires_ms"]:
                    log(f"{e.name}/{e.key}: newer live credential found; keeping it")
                    continue
                blob = doc.setdefault(e.key, {"type": "oauth"})
                blob["access"] = new_access
                blob["refresh"] = new_refresh
                blob["expires"] = int(new_expires_ms)
                write_json_atomic(e.live, doc)
                update_backup(e, doc)
                log(f"{e.name}/{e.key}: refreshed (~{days_left(new_expires_ms):.1f}d left)")

    finally:
        os.close(lock)
    return rc




def main(argv=None) -> int:
    p = argparse.ArgumentParser(prog="api-auth-sync", description=__doc__)
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("status", help="show per-entry token expiry (no values)")
    sub.add_parser("migrate", help="writeBoundary hook: make live auth files real files")
    sub.add_parser("guard", help="alias of migrate")
    sub.add_parser("refresh", help="refresh stale token lineages (network)")
    args = p.parse_args(argv)
    load_config()
    table = {
        "status": cmd_status,
        "migrate": cmd_migrate,
        "guard": cmd_migrate,
        "refresh": cmd_refresh,
    }
    return table[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
