apiVersion: ENC[AES256_GCM,data:PBU=,iv:FfVwaMPrdnHUxcJk3dl7Nzi75qGObU0w1mlMXxZ7vyY=,tag:GEj9fwI8cNeIw0GQ4Zzrew==,type:str]
kind: ENC[AES256_GCM,data:+Ts+QoI70cJz,iv:+6fPApt2vprTJB7iBd4cAUSB4p2rpinoRC5W8o3n76Q=,tag:0iksX3a18IgoEvD3f4UyOw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qJk0PGCY55hQ25dPag==,iv:0D/E4yHA5Qkh9/wBh3JXhg/fXXkCQaAvG7CmxR5WDfM=,tag:7aThc2ODSuIbGCDzVx6bZg==,type:str]
    namespace: ENC[AES256_GCM,data:ETmq8S1w,iv:bpOdKtCh7WgkB8rjwyuqn7+sA+/Ua2XIOuPCwSfsr/k=,tag:yfMyRQP9OTkCug4dCVwc9A==,type:str]
data:
    garage.toml: ENC[AES256_GCM,data:/3iUOjGi5oJkU5YhrYuNnf+9W1RelETi2oH3a2RF1eNd0OhvN0oUmZdtRi+4/5/tfBFwxOlkEv9TUCy8kANGCQbS6HzaSEJVnSIzxbTdkY4gWUCV8QYKNRRZQfMKllkC2X2YLkvQAnSVRe7VPg2H+NC8wSl5j2dq5Eax+whkQ8fqZoChBGzbba2+QXv7W/SXalXlez/liboozqJgvL6q5qLzUjyJtR3ANYa8hptoPUhTiVHvGem4L4ps97Ewqq1AA7tZTaDcgjaRl7ZRHdwfb8bypWLI9c33OsIhXXPimAVVXrS3UnNZ/FwIKhCfD35kvJU+CeLAC2vKZ/KkmPNg+QDjQ9GlmOx2lufLHxRXXw67lZo3SQ5EErnkfJ0gXsrwYNkkB8Q0BuPZMmRZDjZWOPZzU5QmhTuMqX+O3yJ273DLdj4EvV/2neGyHel6YmWf7LgsY4EPa6/iUFDEuWNZeBpPF93x/hhD3G/lqzckLCQqS/p+YA4uy4HbDhCkv1ngQvx0m4GbntUn58ed9sa4J4rBrBeY1oLf04x9KZ8q2PTEofyr8UaQ2el/nzOPF1bT8BQraoTEBDoNZUIAPBMuFkEsrk6YBozUamAwrx/MphQYqX5c97VELYsh1jixLuMzfyK9cTagUE9CzYNU77OhUUF8kuinh0fonSAaTNBkLnCVuClu4v2e7x2wqL6Yc3EdRmCFD6PnGzDadcGCfVosW6B4hghXXqIGgPYFFfrZVhYEDnjvqpfKkxiZwG7DlPNBz5koQ9wXZmpldMuD08rtkZIAcjeM0AtB04S9nHw6ias=,iv:QR2hds+ZGSDDpYXKEXktOldZBGZIGuuKcx8X8yvJAjA=,tag:U4Ip55iQ5r9Xqcv+FtchEA==,type:str]
sops:
    age:
        - recipient: age1vshrm5lkqp3s0v3wgnhyjf8dlvhnf53u9779xs7ntycpeleud38q48eq53
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWTRhZHJOQktoeWlvS3Fw
            RXNXbmhEdVFBOWxmMlR4L0xWaWY1VXVMNVYwCit6OVhVSi9ZL1VLbVR5WWNKRExj
            Z3NvUE5XR2t3ekNuQUxaVnVSa0k1UU0KLS0tIENYWmkxdjk1RFpFdXFuSEQwVitV
            dzZnR05ZdFVWRVpzS3B6Uys5TVB5bm8KUYOuXaJd1ocS/WhAkpGYdWFN53qB416c
            Z7Eyk9AdGdCLZy8r2BQRpH+J5vYHUj3XXaI6Y84SkdZavRi/Mh5K7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15xalxx87nllapelvvd7c435ktjcd84u96238g8mek26mg9aljuvqhm60uj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTmRnVkI0QTI4NmEzUUVv
            VVlxako1TUtDL3FyczFUMzFNY3MrV05tRzNrCmR4bUZic0lDVlgyL1pzRWVwcVN1
            M0dKYUtkbitCR0Z0ZitvWlpxV2R6ZzQKLS0tIEY3QS9pUDBUSzRNTFlTNEJ1c0cx
            YlNGVHdnbkVFVkR4TFQvZHI5VmhZZkUKYvuOgimCi5i6OZ8rpCvIsWHNr+JARa7L
            F+kHV2S/WaY+ixUPfeXlHkQgmVgblrTfi7gHAEZXsuMpocguSglsQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fc3lwl2pzxrlsjra4m3rx850tl4caq7ryp64crcleh05nez445fswzw354
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcnZSN1B6bmdlV0ZVRVNV
            b3hhYUQ4bm9zdmpkK0FQSlF4d0MrbzhyWFJBCjFvVXZWSTM3OHZSZDBPUGM0YjYr
            UG1oSkRUdm40Vm5SMm9keUhRbDd3VVEKLS0tIE1BL1BOTitSd243NmJMYlRteGY4
            WVVzb1J3WlZub0pUWmdvQ21FZGpTZDQKC6NBkqP1RKwjRQ9yhgOlKBQAmh1IPlkQ
            izKbiS2faUWRSLHo1zAvzt/SpKG01wTsOi6syYUrTDPFfHAG956mCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T07:49:04Z"
    mac: ENC[AES256_GCM,data:/co+mMTQ7Bnps9/5Prp8gDDawvT02Hz8mD7eRqS7CgzKMS1EQATlpyMWa2++Egx5Hs57wwgJDLcslOxAW0ro7dEB1p55hl6IsJontCwSVBZJVfw6EngLcSq+5vBhYt/wWm8DosYIUveeSRXVbmj2T//j7Ked9h5EApBdthh+PU0=,iv:mIdUvbzCiOvWPTbMrNW4yFGreWcI7MEbycaLVd9QtgQ=,tag:Sa26YYgZL/D9ZemqDp/CHA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
