#!@bash@
#################################################
#
## Autostart Most Used Apps
#
#################################################
#~ wait 3 seconds
sleep 3

# file syntax: workspace_number:monitor_name|kind:value|app_with_args
# example    : 1:HDMI-1|app_id:firefox|firefox --new-window https://www.google.com

[[ -e "$XDG_RUNTIME_DIR/.autostart" ]] && exit
while IFS= read -r line; do
    [[ -z "$line" || "$line" =~ ^# ]] && continue

    IFS='|' read -r ws option app <<<"$line"
    IFS=':' read -r workspace monitor <<<"$ws"
    read -r value <<<"$option"

    [[ "$workspace" != "none" ]] && @hyprctl@ keyword workspace "$workspace,monitor:$monitor,name:$workspace-$monitor"
    [[ "$value" != "none" ]] && @hyprctl@ keyword windowrulev2 "workspace silent name:$workspace-$monitor,class:^($value)$"
    eval "$app" &
    disown
    sleep 1
done <"$HOME/.autostart.hyprland"
touch "$XDG_RUNTIME_DIR/.autostart"

