#!/usr/bin/env python3
"""codex-auth-sync — keep Codex/OpenAI OAuth tokens fresh for opencode + prime-agent.

Why: access tokens live 10 days; refresh tokens are single-use and rotate on
every refresh. The live auth.json files must therefore be the source of truth,
and sops only acts as seed + sync mirror.

Subcommands:
  status    per-entry token expiry in days (no values printed)
  migrate   HM writeBoundary hook: ensure live auth files are REAL regular
            files (convert sops symlinks), freshest-wins restore from
            backup/seed/sops, then update backups
  guard     alias of migrate (cheap, no network)
  refresh   refresh stale token lineages via auth.openai.com, write back
            atomically, update backups, then best-effort sync to the sops repo
  sync      re-encrypt fresher live tokens back into the sops repo + git commit/push

Security: token/key values are NEVER printed or logged; only paths, provider
keys and expiry deltas. All writes are atomic (tmp + fsync + rename), mode 0600.
"""

import argparse
import fcntl
import json
import os
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path

# NOTE: this file contains NO machine-specific paths. Every path comes from the
# JSON config pointed to by $CODEX_AUTH_CONFIG (generated by modules/home/codex-auth.nix).
CONFIG_ENV = "CODEX_AUTH_CONFIG"

CLIENT_ID = "app_EMoamEEZ73f0CkXaXp7hrann"  # public constant from openai/codex source
TOKEN_URL = "https://auth.openai.com/oauth/token"
REFRESH_MARGIN_SECS = 48 * 3600
DEFAULT_TTL_SECS = 10 * 86400  # observed access-token lifetime
PERMANENT_CODES = {
    "refresh_token_expired",
    "refresh_token_invalidated",
    "refresh_token_reused",
    "invalid_grant",
    "app_session_terminated",
}
GIT_SYNC = os.environ.get("CODEX_AUTH_SYNC_GIT", "1") != "0"
GIT_PUSH = os.environ.get("CODEX_AUTH_SYNC_PUSH", "1") != "0"


@dataclass
class Entry:
    name: str
    live: Path          # live auth file (real file, never a symlink)
    key: str            # provider key inside the JSON doc
    secret: Path        # repo sops secret path (seed + sync mirror)


# Runtime configuration (single source of truth: the JSON config file).
CONFIG: dict = {}
DOTFILES: Path = Path("/dev/null")  # overwritten by load_config(); never used before that
STATE_DIR: Path = Path("/dev/null")
BACKUP_DIR: Path = Path("/dev/null")
ENTRIES: list = []


def load_config() -> None:
    """Populate DOTFILES / STATE_DIR / BACKUP_DIR / ENTRIES from the JSON config."""
    global CONFIG, DOTFILES, STATE_DIR, BACKUP_DIR, ENTRIES
    raw = os.environ.get(CONFIG_ENV)
    if not raw:
        sys.exit(
            f"error: {CONFIG_ENV} is not set. Point it at the JSON config generated by "
            "modules/home/codex-auth.nix (programs.codex-auth), e.g. the profile-wrapped "
            "binary already has it set."
        )
    try:
        with open(raw) as f:
            CONFIG = json.load(f)
    except (OSError, json.JSONDecodeError) as ex:
        sys.exit(f"error: cannot read config {raw}: {ex}")

    if not CONFIG.get("dotfiles"):
        sys.exit("error: config is missing required key 'dotfiles'")
    DOTFILES = Path(CONFIG["dotfiles"])

    state = CONFIG.get("state_dir") or (
        Path(os.environ.get("XDG_STATE_HOME") or (Path.home() / ".local/state")) / "codex-auth"
    )
    STATE_DIR = Path(state)
    BACKUP_DIR = STATE_DIR / "backup"

    for e in CONFIG.get("entries") or []:
        ENTRIES.append(Entry(str(e["name"]), Path(e["live"]), str(e["key"]), Path(e["secret"])))
    if not ENTRIES:
        sys.exit("error: config defines no entries")


def log(msg: str) -> None:
    stamp = time.strftime("%Y-%m-%dT%H:%M:%S%z")
    print(f"[codex-auth-sync {stamp}] {msg}", flush=True)


def ensure_dirs() -> None:
    for d in (STATE_DIR, BACKUP_DIR):
        d.mkdir(parents=True, exist_ok=True)
        try:
            d.chmod(0o700)
        except OSError:
            pass


def norm_ms(v) -> float:
    """Normalize an expiry value to epoch milliseconds (accepts s or ms)."""
    try:
        v = float(v)
    except (TypeError, ValueError):
        return 0.0
    if v <= 0:
        return 0.0
    if v < 1e12:  # seconds
        v *= 1000.0
    return v


def creds_of(doc, key: str):
    """Extract the normalized OAuth triple for one provider key. No values leave this function."""
    if not isinstance(doc, dict):
        return None
    blob = doc.get(key)
    if not isinstance(blob, dict):
        return None
    refresh = blob.get("refresh")
    if not refresh or not isinstance(refresh, str):
        return None
    return {
        "access": blob.get("access") or "",
        "refresh": refresh,
        "expires_ms": norm_ms(blob.get("expires")),
        "account_id": blob.get("accountId"),
    }


def load_doc(path: Path):
    """Read a JSON doc through symlinks. Returns (doc, err_reason)."""
    try:
        return json.loads(path.read_text()), None
    except FileNotFoundError:
        return None, "missing"
    except json.JSONDecodeError as ex:
        return None, f"invalid json ({ex.msg})"
    except OSError as ex:
        return None, f"unreadable ({ex.strerror})"


def write_json_atomic(path: Path, doc, mode: int = 0o600) -> None:
    """Atomically write a real regular file; os.replace over a symlink replaces the link itself."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.parent / f".{path.name}.tmp-{os.getpid()}"
    with open(tmp, "w") as f:
        json.dump(doc, f, indent=2)
        f.write("\n")
        f.flush()
        os.fsync(f.fileno())
    os.chmod(tmp, mode)
    os.replace(tmp, path)


def write_bytes_atomic(path: Path, data: bytes, mode: int = 0o600) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.parent / f".{path.name}.tmp-{os.getpid()}"
    with open(tmp, "wb") as f:
        f.write(data)
        f.flush()
        os.fsync(f.fileno())
    os.chmod(tmp, mode)
    os.replace(tmp, path)


def days_left(expires_ms: float) -> float:
    return (expires_ms - time.time() * 1000) / 86_400_000.0


# ---------------------------------------------------------------- sops / git

def sops_decrypt(secret: Path):
    """Decrypt a sops file to memory. NEVER log or print the plaintext."""
    sops = shutil.which("sops")
    if not sops:
        return None, "sops not in PATH"
    try:
        r = subprocess.run([sops, "--decrypt", str(secret)],
                           capture_output=True, timeout=60)
    except subprocess.TimeoutExpired:
        return None, "sops decrypt timeout"
    if r.returncode != 0:
        return None, f"sops decrypt failed (rc={r.returncode})"
    try:
        return json.loads(r.stdout.decode()), None
    except json.JSONDecodeError:
        return None, "decrypted payload is not json"


def sops_encrypt_stdin(secret: Path, plaintext: str):
    """Encrypt plaintext as if it lived at `secret` (keeps format + metadata path)."""
    sops = shutil.which("sops")
    if not sops:
        return None, "sops not in PATH"
    try:
        r = subprocess.run(
            [sops, "--encrypt", "--filename-override", str(secret)],
            input=plaintext.encode(), capture_output=True, timeout=60)
    except subprocess.TimeoutExpired:
        return None, "sops encrypt timeout"
    if r.returncode != 0:
        return None, f"sops encrypt failed (rc={r.returncode})"
    return r.stdout, None


def git_run(args, timeout=120):
    return subprocess.run(["git", "-C", str(DOTFILES)] + args,
                          capture_output=True, text=True, timeout=timeout)


def repo_dirty() -> bool:
    """True if the repo has ANY staged/unstaged/untracked changes."""
    r = git_run(["status", "--porcelain"])
    return r.returncode == 0 and r.stdout.strip() != ""


# ---------------------------------------------------------------- candidates

class Source:
    __slots__ = ("name", "path", "doc", "creds", "err")

    def __init__(self, name, path, doc, err):
        self.name, self.path, self.doc, self.err = name, path, doc, err
        self.creds = creds_of(doc, doc_key.get(path)) if doc is not None else None


# map path -> provider key (needed by Source before entries are wired in)
doc_key: dict = {}


def entry_paths(e: Entry):
    return {
        "live": e.live,
        "backup": BACKUP_DIR / f"{e.name}.json",
        "seed": STATE_DIR / f"{e.name}.json",
    }


def collect_sources(e: Entry):
    doc_key[e.live] = e.key
    doc_key[BACKUP_DIR / f"{e.name}.json"] = e.key
    doc_key[STATE_DIR / f"{e.name}.json"] = e.key
    out = []
    for name, path in entry_paths(e).items():
        doc, err = load_doc(path)
        out.append(Source(name, path, doc, err))
    if e.secret.exists():
        doc, err = sops_decrypt(e.secret)
        s = Source("sops", e.secret, doc, err)
        s.creds = creds_of(doc, e.key) if doc is not None else None
        out.append(s)
    return out


def pick_freshest(sources):
    valid = [s for s in sources if s.creds is not None]
    if not valid:
        return None
    return max(valid, key=lambda s: (s.creds["expires_ms"], s.name == "live"))


def update_backup(e: Entry, doc) -> None:
    """Keep the state backup in sync with a fresher live doc."""
    bpath = BACKUP_DIR / f"{e.name}.json"
    bdoc, _ = load_doc(bpath)
    lc = creds_of(doc, e.key)
    bc = creds_of(bdoc, e.key) if bdoc is not None else None
    if lc and (bc is None or lc["expires_ms"] > bc["expires_ms"]):
        write_json_atomic(bpath, doc)
        log(f"{e.name}: backup updated (~{days_left(lc['expires_ms']):.1f}d left)")


# ---------------------------------------------------------------- commands

def cmd_status(_args) -> int:
    ensure_dirs()
    for e in ENTRIES:
        print(f"{e.name} (provider key '{e.key}'):")
        for s in collect_sources(e):
            if s.creds is None:
                print(f"  {s.name:7s} {s.path}: unavailable ({s.err or 'no refresh token'})")
            else:
                print(f"  {s.name:7s} {s.path}: ~{days_left(s.creds['expires_ms']):.1f}d left")
    return 0


def cmd_migrate(_args) -> int:
    """writeBoundary hook: live paths must be real regular files, freshest wins."""
    ensure_dirs()
    rc = 0
    for e in ENTRIES:
        sources = collect_sources(e)
        live = next(s for s in sources if s.name == "live")
        bad = e.live.is_symlink() or live.doc is None
        if bad:
            reason = "symlink" if e.live.is_symlink() else (live.err or "unreadable")
            best = pick_freshest(sources)
            if best is not None and best.doc is not None:
                write_json_atomic(e.live, best.doc)
                log(f"{e.name}: live file was {reason}; converted to real file from '{best.name}'")
            else:
                log(f"{e.name}: live file was {reason} and no usable source found")
                rc = 1
                continue
        doc, _ = load_doc(e.live)
        if doc is None:
            log(f"{e.name}: live file unreadable after migration")
            rc = 1
            continue
        update_backup(e, doc)
    return rc


def acquire_lock():
    fd = os.open(STATE_DIR / "refresh.lock", os.O_CREAT | os.O_RDWR, 0o600)
    try:
        fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
        return fd
    except BlockingIOError:
        os.close(fd)
        return None


def http_refresh(refresh_token: str):
    """POST the refresh request. Raises PermanentError / TransientError. Never logs bodies."""
    payload = json.dumps({
        "grant_type": "refresh_token",
        "client_id": CLIENT_ID,
        "refresh_token": refresh_token,
    }).encode()
    req = urllib.request.Request(TOKEN_URL, data=payload,
                                 headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.loads(r.read().decode())
    except urllib.error.HTTPError as ex:
        try:
            code = json.loads(ex.read().decode()).get("code", "")
        except Exception:
            code = ""
        if ex.code in (400, 401) and code in PERMANENT_CODES:
            raise PermanentError(code or f"http {ex.code}")
        raise TransientError(code or f"http {ex.code}")
    except urllib.error.URLError as ex:
        raise TransientError(str(ex.reason))
    except TimeoutError:
        raise TransientError("timeout")


class PermanentError(Exception):
    pass


class TransientError(Exception):
    pass


def cmd_refresh(args) -> int:
    ensure_dirs()
    lock = acquire_lock()
    if lock is None:
        log("another refresh is already running; exiting")
        return 0
    rc = 0
    try:
        if GIT_SYNC and DOTFILES.exists() and shutil.which("git"):
            if repo_dirty():
                log("dotfiles repo has uncommitted changes; skipping git pull to protect your index")
            else:
                r = git_run(["pull", "--rebase", "--autostash"])
                if r.returncode != 0:
                    log(f"git pull failed (rc={r.returncode}); continuing with local state")

        # gather freshest state per entry, adopting non-live sources into live
        plan = []
        for e in ENTRIES:
            sources = collect_sources(e)
            best = pick_freshest(sources)
            if best is None:
                log(f"{e.name}: no usable refresh token found anywhere; skipping")
                rc = max(rc, 1)
                continue
            if best.name != "live" and best.doc is not None:
                write_json_atomic(e.live, best.doc)
                log(f"{e.name}: adopted fresher tokens from '{best.name}'")
            doc, err = load_doc(e.live)
            if doc is None:
                log(f"{e.name}: live file unreadable ({err})")
                rc = max(rc, 1)
                continue
            plan.append((e, doc, creds_of(doc, e.key)))

        # group entries by refresh token lineage: same token -> exactly ONE network call
        groups = {}
        for e, doc, creds in plan:
            if creds is None:
                log(f"{e.name}: live doc has no refresh token under '{e.key}'")
                rc = max(rc, 1)
                continue
            groups.setdefault(creds["refresh"], []).append((e, doc, creds))

        now_ms = time.time() * 1000
        for token, members in groups.items():
            freshest = max(members, key=lambda m: m[2]["expires_ms"])
            left_secs = freshest[2]["expires_ms"] / 1000.0 - time.time()
            if left_secs > REFRESH_MARGIN_SECS:
                log(f"{freshest[0].name}: token fresh (~{left_secs / 86400:.1f}d left); no network call")
                continue
            try:
                resp = http_refresh(token)
            except PermanentError as ex:
                log(f"{freshest[0].name}: PERMANENT refresh failure ({ex}); browser re-login required")
                rc = 3
                continue
            except TransientError as ex:
                log(f"{freshest[0].name}: transient refresh failure ({ex}); will retry later")
                rc = max(rc, 4)
                continue
            new_access = resp.get("access_token")
            if not new_access:
                log(f"{freshest[0].name}: refresh response had no access_token; retry later")
                rc = max(rc, 4)
                continue
            new_refresh = resp.get("refresh_token") or token  # rotation: persist the new one
            new_expires_ms = now_ms + float(resp.get("expires_in") or DEFAULT_TTL_SECS) * 1000.0
            for e, doc, _creds in members:
                blob = doc.setdefault(e.key, {})
                blob["access"] = new_access
                blob["refresh"] = new_refresh
                blob["expires"] = int(new_expires_ms)
                write_json_atomic(e.live, doc)
                update_backup(e, doc)
                log(f"{e.name}/{e.key}: refreshed (~{days_left(new_expires_ms):.1f}d left)")

        if rc == 0 and GIT_SYNC:
            rc = max(rc, cmd_sync(argparse.Namespace(dry_run=False, quiet=True)))
    finally:
        os.close(lock)
    return rc


def cmd_sync(args) -> int:
    """Mirror fresher live tokens back into the sops repo (encrypt + commit + push)."""
    ensure_dirs()
    if not DOTFILES.exists():
        log(f"dotfiles repo not found at {DOTFILES}; sync skipped")
        return 0
    if not shutil.which("sops"):
        log("sops not in PATH; sync skipped")
        return 0
    dry = bool(getattr(args, "dry_run", False))
    quiet = bool(getattr(args, "quiet", False))
    committed = []

    if GIT_SYNC and not dry and shutil.which("git"):
        if repo_dirty():
            log("dotfiles repo has uncommitted changes; skipping git pull to protect your index")
        else:
            r = git_run(["pull", "--rebase", "--autostash"])
            if r.returncode != 0 and not quiet:
                log(f"git pull failed (rc={r.returncode}); continuing")

    for e in ENTRIES:
        if e.live.is_symlink():
            log(f"{e.name}: live file is a symlink; refusing to sync from it")
            continue
        live_doc, err = load_doc(e.live)
        if live_doc is None:
            log(f"{e.name}: live file unreadable ({err}); sync skipped")
            continue
        repo_doc, derr = sops_decrypt(e.secret)
        if repo_doc is None:
            if not quiet:
                log(f"{e.name}: repo secret unavailable ({derr}); will re-encrypt from live")
            repo_c = None
        else:
            repo_c = creds_of(repo_doc, e.key)
        live_c = creds_of(live_doc, e.key)
        if live_c is None:
            log(f"{e.name}: live doc has no refresh token under '{e.key}'; sync skipped")
            continue
        if repo_c is not None and repo_c["expires_ms"] >= live_c["expires_ms"]:
            if not quiet:
                log(f"{e.name}: repo copy up to date; nothing to do")
            continue
        if dry:
            log(f"{e.name}: would re-encrypt live tokens into {e.secret} and commit")
            continue
        data, eerr = sops_encrypt_stdin(e.secret, json.dumps(live_doc, indent=2) + "\n")
        if data is None:
            log(f"{e.name}: encryption failed ({eerr}); sync aborted for this entry")
            continue
        write_bytes_atomic(e.secret, data, 0o600)
        r = git_run(["add", str(e.secret.relative_to(DOTFILES))])
        if r.returncode != 0:
            log(f"{e.name}: git add failed (rc={r.returncode})")
            continue
        r = git_run(["commit", "-m", f"chore(codex-auth-sync): refresh {e.name} codex tokens",
                     "--", str(e.secret.relative_to(DOTFILES))])
        if r.returncode != 0:
            out = (r.stdout or "") + (r.stderr or "")
            if "nothing to commit" in out:
                log(f"{e.name}: nothing new to commit")
            else:
                log(f"{e.name}: git commit failed (rc={r.returncode})")
            continue
        committed.append(e.name)
        log(f"{e.name}: refreshed tokens committed to repo")

    if committed and GIT_PUSH and shutil.which("git") and not dry:
        r = git_run(["push"])
        if r.returncode != 0:
            log("git push failed; commits stay local (will retry next run)")
        else:
            log(f"pushed {len(committed)} secret update(s) to origin")
    return 0


def main(argv=None) -> int:
    p = argparse.ArgumentParser(prog="codex-auth-sync", description=__doc__)
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("status", help="show per-entry token expiry (no values)")
    sub.add_parser("migrate", help="writeBoundary hook: make live auth files real files")
    sub.add_parser("guard", help="alias of migrate")
    sub.add_parser("refresh", help="refresh stale token lineages (network)")
    s = sub.add_parser("sync", help="mirror fresher live tokens back into the sops repo")
    s.add_argument("--dry-run", action="store_true", help="report actions without writing")
    args = p.parse_args(argv)
    load_config()
    if not os.environ.get("SOPS_AGE_KEY_FILE"):
        keyfile = CONFIG.get("age_key_file")
        if keyfile and Path(keyfile).exists():
            os.environ["SOPS_AGE_KEY_FILE"] = str(keyfile)
    table = {
        "status": cmd_status,
        "migrate": cmd_migrate,
        "guard": cmd_migrate,
        "refresh": cmd_refresh,
        "sync": cmd_sync,
    }
    return table[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
