#!@bash@
[[ $# -eq 0 ]] && exit 1
for arg in "$@"; do
    [[ "$arg" =~ '#' ]] && {
        dir="${arg%#*}"
        flake="${arg#*#}"
        break
    }
done
[[ -z "$dir" ]] && dir="$HOME/Projects/000_myprojects/dotfiles.nix"
[[ -z "$flake" ]] && flake="$1"
pushd "$dir" || exit
pacman -Q | sort | uniq > hosts/"$flake"/arch-pkglist.txt
clear
[[ "$*" =~ "--update-flake" ]] && nix flake update
home-manager switch --no-out-link --flake "$dir#$flake" --impure
read -r -p "Do you want to read news?: " choice
[[ "$choice" =~ [yY] ]] && home-manager news --no-out-link --flake "$dir#$flake"
read -r -p "Do you want to clear unused files?: " choice
[[ "$choice" =~ [yY] ]] && nix-collect-garbage -d
popd || exit
