#!@bash@

GPU_ID="0000:01:00.0"
AUDIO_ID="0000:01:00.1"

if [[ "$1" == "vfio-pci" ]]; then
	sudo modprobe -r amdgpu
	echo $GPU_ID   | sudo tee /sys/bus/pci/devices/$GPU_ID/driver/unbind
	echo $AUDIO_ID | sudo tee /sys/bus/pci/devices/$AUDIO_ID/driver/unbind
	echo $GPU_ID   | sudo tee /sys/bus/pci/drivers/vfio-pci/bind
	echo $AUDIO_ID | sudo tee /sys/bus/pci/devices/vfio-pci/bind
	echo 1 | sudo tee /sys/bus/pci/rescan
else
	sudo modprobe amdgpu
	echo $GPU_ID   | sudo tee /sys/bus/pci/devices/$GPU_ID/driver/unbind
	echo $AUDIO_ID | sudo tee /sys/bus/pci/devices/$AUDIO_ID/driver/unbind
	echo $GPU_ID   | sudo tee /sys/bus/pci/drivers/amdgpu/bind
	echo $AUDIO_ID | sudo tee /sys/bus/pci/devices/snd-hda-intel/bind
	echo 1 | sudo tee /sys/bus/pci/rescan
fi
