#!@bash@
[[ $# -eq 0 ]] && exit 1
pushd "$HOME"/Projects/000_myprojects/dotfiles.nix || exit
rpm -qa --queryformat '%{NAME}\n' | sort | uniq > hosts/msi-h510m-pro-fedora/fedora-rpm-pkglist.txt
clear
[[ "$*" =~ "--update-flake" ]] && nix flake update
home-manager switch --no-out-link --flake "$1"
read -r -p "Do you want to read news?: " choice
[[ "$choice" =~ [yY] ]] && home-manager news --no-out-link --flake "$1"
read -r -p "Do you want to clear unused files?: " choice
[[ "$choice" =~ [yY] ]] && nix-collect-garbage -d
popd || exit
